spring:
  profiles:
  - prod
  - dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://0.0.0.0:5432/mecanica
    password: 123
    username: trainee
  jpa:    
    database: POSTGRESQL
    show-sql: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
---
spring:
  profiles:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2://0.0.0.0:5432/mecanica
    password: sa
    username: sa
  jpa:    
    database: H2
    show-sql: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update